# Introdução ao Julia

Como o JuMP está escrito na linguagem `Julia`, é importante ter algum conhecimento básico
dela antes de começar a aprender a usar o JuMP.

**Obs**
Este tutorial foi pensado como um curso rápido e minimalista sobre os fundamentos do Julia.
No [site do Julia](https://julialang.org/learning/) há várias introduções mais abrangentes à linguagem.

## Instalando o Julia

Para instalar o Julia, [baixe a versão estável mais recente](https://julialang.org/downloads/),
e siga as [instruções de instalação específicas para a plataforma](https://julialang.org/downloads/platform/).

**Dica**
    Se você está em dúvida, provavelmente a versão de 64 bits é a certa para seu computador.

Em seguida, você precisa de um ambiente de desenvolvimento. O VS Code é uma escolha popular, então siga
[essas instruções de instalação](https://www.julia-vscode.org/docs/stable/gettingstarted/).

O Julia também pode ser usado com [notebooks Jupyter](https://github.com/JuliaLang/IJulia.jl)
ou - para quem quiser se aventurar um pouco mais - notebooks do [Pluto.jl](https://github.com/fonsp/Pluto.jl).

## O REPL do Julia

A principal forma de interagir com o Julia é através do seu REPL (Read Eval Print Loop).
Para acessar o REPL, inicie o executável do Julia para chegar ao prompt
`julia>`, e então digite:

In [2]:
1 + 1

2

Para programas maiores, escreva um script como um arquivo de texto, e execute
esse arquivo usando:
```julia
julia> include("caminho/para/arquivo.jl")
```

**Atenção:**
    Devido à latência de inicialização do Julia, executar scripts pela linha de comando do seu sistema operacional é lento, ou seja, evite fazer isso:
    ```
    $ julia caminho/para/arquivo.jl
    ```
    Use o REPL ou um notebook em vez disso, e leia sobre o ["time-to-first-solve"](https://jump.dev/JuMP.jl/stable/tutorials/getting_started/performance_tips/#The-%22time-to-first-solve%22-issue) para mais informações.

### Blocos de código nesta documentação

Nesta documentação, você verá uma mistura de exemplos de código com e sem o
`julia>`.

O prompt Julia é usado principalmente para demonstrar trechos curtos de código, e a
saída é exatamente o que você verá se executar a partir do REPL.

Blocos sem o `julia>` podem ser copiados e colados no REPL, mas são
usados porque possibilitam uma saída mais rica, como gráficos ou LaTeX, para ser exibida
nas versões online e em [PDF](https://jump.dev/JuMP.jl/stable/JuMP.pdf)
da documentação. Se você executá-los no REPL, pode ver uma saída diferente.

## Onde obter ajuda

* Na documentação oficial
  * [da biblioteca JuMP](https://jump.dev/JuMP.jl/stable/)
  * [da linguagem Julia](https://docs.julialang.org/en/v1/)
  * [para instalar](https://docs.jupyter.org/en/latest/install.html#install) e [usar](https://jupyter-notebook.readthedocs.io/en/latest/notebook.html#notebook-user-interface) notebooks jupyter
* Pergunte (ou pesquise) [no fórum da comunidade Julia](https://discourse.julialang.org)
  * Se a pergunta estiver relacionada ao JuMP, pergunte na seção [Optimization (Mathematical)](https://discourse.julialang.org/c/domain/opt/13)
    ou marque sua pergunta com "jump"
* Diretamente no REPL

Para acessar a ajuda da própria linguagem, no REPL ou num notebook,
digite `?` para ativar o _help-mode_, seguido da função a ser pesquisada.
Por exemplo, ao pesquisar a função `print`, você obterá:
```julia
help?> print
search: print println printstyled sprint isprint prevind parentindices precision escape_string

  print([io::IO], xs...)

  Write to io (or to the default output stream stdout if io is not given) a canonical
  (un-decorated) text representation. The representation used by print includes minimal
  formatting and tries to avoid Julia-specific details.

  print falls back to calling show, so most types should just define show. Define print
  if your type has a separate "plain" representation. For example, show displays strings
  with quotes, and print displays strings without quotes.

  See also println, string, printstyled.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> print("Hello World!")
  Hello World!
  julia> io = IOBuffer();

  julia> print(io, "Hello", ' ', :World!)

  julia> String(take!(io))
  "Hello World!"
```

**Obs:** Em geral, ao utilizar a ajuda da linguagem, haverá muito mais informações do que você precisa.

## Números

Como queremos resolver problemas de otimização, vamos usar muita
matemática. Felizmente, o Julia é ótimo para matemática, com todos
os operadores usuais:

In [3]:
1 + 1
1 - 2
2 * 2
4 / 5
3^2

9

O REPL do Julia não imprimiu `.0` após alguns dos números.
Como Julia é uma linguagem dinâmica, você não precisa declarar explicitamente o tipo de uma variável.
No entanto, nos bastidores, o Julia está atribuindo a cada variável um tipo.
O tipo de qualquer valor em Julia pode ser obtido usando a função `typeof`:

In [4]:
typeof(1)
typeof(1.0)

Float64

Aqui, `1` é um `Int64`, que é um número inteiro que ocupa 64 bits de memória,
e `1.0` é um `Float64`, que é um número de ponto flutuante que ocupa 64 bits de memória.

**Dica**
    Se você não está familiarizado com números de ponto flutuante, leia a seção Números de ponto flutuante logo abaixo.

Criamos números complexos usando `im`:

In [7]:
x = 2 + 1im
println(real(x))
println(imag(x))
println(typeof(x))
x * (1 - 2im)

2
1
Complex{Int64}


4 - 3im

**Informação**
    As chaves envolvem o que chamamos de _parâmetros_ de um tipo. Você pode
    ler `Complex{Int64}` como "um número complexo, onde as partes real e
    imaginária são representadas por `Int64`."
    Por outro lado, `typeof(1.0 + 2.0im)`, será `Complex{Float64}`,
    o que quer dizer que `1.0 + 2.0im` é um número complexo
    cujas as partes real e imaginária são representadas por `Float64`.

Existem também coisas interessantes, como uma representação irracional ("abstrata") de π.

In [17]:
π 

π = 3.1415926535897...

**Dica**
    Para obter π (e a maioria das outras letras gregas), digite `\pi` e
    pressione `[TAB]`.

In [18]:
typeof(π)

Irrational{:π}

No entanto, se fizermos cálculos com números irracionais, eles são
convertidos para `Float64`:

In [19]:
typeof(2π / 3)

Float64

### Números de ponto flutuante

**Aviso**
    Se você não está familiarizado com números de ponto flutuante, leia esta seção com atenção.

Um `Float64` é uma [representação de ponto flutuante](https://en.wikipedia.org/wiki/Floating-point_arithmetic)
de um número real usando 64 bits de informação.

Por ser uma aproximação, coisas que sabemos serem verdadeiras na matemática não
são necessariamente verdadeiras em um computador. Por exemplo:

In [22]:
# O operador "==" testa se dois valores são iguais
0.1 * 3 == 0.3

false

Um exemplo mais complicado é:

In [23]:
sin(2π / 3) == √3 / 2

false

**Dica**
    A raiz `√` é obtida digitando `\sqrt` e depois `[TAB]`.

Vamos ver quais são as diferenças:

In [25]:
println(0.1 * 3 - 0.3)
sin(2π / 3) - √3 / 2

5.551115123125783e-17


1.1102230246251565e-16

Elas são pequenas, mas não são zero.

Uma maneira de explicar essa diferença é considerar como escreveríamos
`1 / 3` e `2 / 3` usando apenas quatro dígitos após o ponto decimal. Escreveríamos
`1 / 3` como `0.3333` e `2 / 3` como `0.6667`. Assim, apesar do fato de
`2 * (1 / 3) == 2 / 3`, `2 * 0.3333 == 0.6666 != 0.6667`.

Vamos tentar novamente usando ≈ (`\approx + [TAB]`) em vez de `==`:

In [26]:
0.1 * 3 ≈ 0.3
sin(2π / 3) ≈ √3 / 2

true

`≈` é uma forma conveniente de chamar a função `isapprox`:

In [27]:
isapprox(sin(2π / 3), √3 / 2; atol = 1e-8)

true

**Atenção**

O uso praticamente universal de ponto flutuante em computação é uma razão pela qual **algoritmos de otimização** (também conhecidos como "_solvers_") têm **tolerâncias** para resolver problemas de otimização.
Um erro comum que é verificar se uma variável binária é igual a 0 usando `value(z) == 0`.
Lembre-se de usar algo como `isapprox` ao comparar números de ponto flutuante.

Observe que `isapprox` sempre retornará `false` se um dos números sendo
comparados for `0` e `atol` for zero (seu valor padrão).

In [28]:
1e-300 ≈ 0.0

false

Portanto, sempre defina um valor não nulo para `atol` se um dos argumentos puder ser zero.

In [52]:
isapprox(1e-9, 0.0; atol = 1e-8)

true

**Dica**
    Se você quiser ler mais sobre este tema, o Gurobi tem uma
    [série de artigos](https://www.gurobi.com/documentation/9.0/refman/num_grb_guidelines_for_num.html)
    discutindo as implicações do uso de ponto flutuante em otimização.

Se você não tiver cuidado, a aritmética de ponto flutuante pode causar uma série de problemas, por exemplo

In [53]:
1 + 1e-16 == 1

true

Surpreendentemente, os números de ponto flutuante não são associativos:

In [54]:
(1 + 1e-16) - 1e-16 == 1 + (1e-16 - 1e-16)

false

É importante observar que esse problema não é específico do Julia. Isso ocorre em
todas as linguagens de programação (experimente em Python, por exemplo).

## Vetores, matrizes e arrays

Como em MATLAB, Julia tem suporte nativo para vetores, matrizes e tensores;
todos são representados por `arrays` de diferentes dimensões.
Vetores são construídos por elementos separados por vírgulas entre colchetes:

In [55]:
b = [5, 6]

2-element Vector{Int64}:
 5
 6

Vetores podem ser acessados por índices, que começam em 1:

In [56]:
b[1]

5

Também podemos acessar "do fim" usando a sintaxe `end`:

In [59]:
b[end-1]

5

Matrizes podem ser construídas com espaços separando as colunas e ponto e vírgula
separando as linhas:

In [62]:
A = [1.0 2.0; 3.0 4.0]

2×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0

Temos álgebra linear básica: por exemplo, podemos calcular a solução do sistema $Ax = b$ usando

In [63]:
x = A \ b

2-element Vector{Float64}:
 -3.9999999999999987
  4.499999999999999

**Info**
    Aqui novamente vemos o efeito de pontos flutuantes: `x` é aproximadamente `[-4, 4.5]`.

In [64]:
A * x

2-element Vector{Float64}:
 5.0
 6.0

In [65]:
A * x ≈ b

true

Observe que, ao multiplicar vetores e matrizes, as dimensões importam. Por
exemplo, você não pode multiplicar um vetor por outro:

In [66]:
try
    b * b
catch err
    showerror(stderr, err)
end

MethodError: no method matching *(::Vector{Int64}, ::Vector{Int64})
The function `*` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...)
   @ Base operators.jl:642
  *(::LinearAlgebra.Diagonal, ::AbstractVector)
   @ LinearAlgebra ~/.julia/juliaup/julia-1.12.5+0.x64.linux.gnu/share/julia/stdlib/v1.12/LinearAlgebra/src/diagonal.jl:330
  *(::LinearAlgebra.UniformScaling, ::AbstractVecOrMat)
   @ LinearAlgebra ~/.julia/juliaup/julia-1.12.5+0.x64.linux.gnu/share/julia/stdlib/v1.12/LinearAlgebra/src/uniformscaling.jl:268
  ...


Já a multiplicação pelo vetor transposto funciona (e o resultado e significado depende da ordem, como esperado):

In [67]:
b' * b

61

In [68]:
b * b'

2×2 Matrix{Int64}:
 25  30
 30  36

## Outros tipos comuns

### Comentários

Embora tecnicamente não seja um tipo, comentários de código começam com o caractere `#`:

In [69]:
1 + 1  # Este é um comentário

2

Comentários de várias linhas começam com `#=` e terminam com `=#`:
```julia
#=
Um comentário
de várias linhas
=#
```

Comentários podem até ser aninhados dentro de expressões. Isso é às vezes útil ao
documentar entradas de funções:

In [70]:
isapprox(
    sin(π),
    0.0;
    #= Precisamos de um atol explícito porque estamos comparando com 0 =#
    atol = 0.001,
)

true

### Strings

Strings são delimitadas por aspas duplas:

In [71]:
typeof("Isso é Julia")

String

Unicode é permitido em strings:

In [72]:
typeof("π é aproximadamente 3.1415")

String

Use `println` para imprimir uma string:

In [73]:
println(1)
println(2/3)

1
0.6666666666666666


In [74]:
println("Olá, Mundo!")

Olá, Mundo!


Use `$()` para **interpolar** valores em uma string:

In [75]:
x = 123
println("O valor de x é: $(x)")

O valor de x é: 123


Use três aspas (como em Python) para criar strings de várias linhas:

In [76]:
s = """
Uma string
com
quatro(!) linhas
"""

println(s)

Uma string
com
quatro(!) linhas



In [77]:
# Vejamos exatamente onde está a quarta linha
# A função `show`, às vezes, dá mais detalhes do que `print`
show(s)

"Uma string\ncom\nquatro(!) linhas\n"

### Símbolos

Os `Symbol`s do Julia são uma estrutura de dados do compilador que representam identificadores Julia (ou seja, nomes de variáveis).
A biblioteca `JuMP`, que permite construir problemas de otimização, usa `Symbol`s para representar variáveis e restrições.

Podemos usar `:` para construir um `Symbol`:

In [78]:
typeof(:x)

Symbol

Você pode pensar em um `Symbol` como uma `String` que ocupa menos memória e que não
pode ser modificada.

In [79]:
println("O valor de x é: $(eval(:x))")

O valor de x é: 123


**Aviso**
    Usamos `eval` aqui apenas para demonstrar como Julia vincula `Symbol`s a variáveis.
    No entanto, evite chamar `eval` em seu código. Geralmente, é um sinal de que seu
    código está fazendo algo que poderia ser mais facilmente alcançado de uma maneira diferente.
    O [Fórum do JuMP](https://jump.dev/forum) é um bom lugar para pedir conselhos sobre
    abordagens alternativas.

É fácil converter entre `String` e `Symbol`:

In [80]:
String(:abc)
Symbol("abc")

:abc

**Dica**
    `Symbol`s são frequentemente (ab)usados para representar uma `String` ou um `Enum`,
    mas estes dois são, em geral, uma melhor escolha.
    O guia de estilo JuMP recomenda reservar `Symbol`s para identificadores.
    Veja [@enum vs. Symbol](https://jump.dev/JuMP.jl/stable/developers/style/#@enum-vs.-Symbol)
    para mais informações.

### Tuplas

Julia usa muito uma estrutura de dados simples chamada **Tuplas**.
Tuplas são coleções **imutáveis** de valores.
Por exemplo:

In [81]:
t = ("hello", 1.2, :foo)
typeof(t)

Tuple{String, Float64, Symbol}

Tuplas podem ser acessadas por índice, como vetores:

In [82]:
t[2]

1.2

In [83]:
t[end]

:foo

E podem ser "desempacotadas" também:

In [84]:
a, b, c = t
b

1.2

Tuplas são parecidas com Vetores, mas como são imutáveis, elas podem ter elementos de tipos diferentes, e cada posição tem o seu tipo.
Ao contrário, se criássemos um Vetor com os elementos da tupla, ele teria o tipo `Vector{Any}`:

In [85]:
v = ["hello", 1.2, :foo]
typeof(v)

Vector{Any} (alias for Array{Any, 1})

Os valores também podem receber nomes, o que é uma maneira conveniente de criar
estruturas de dados leves.
Isto cria uma `NamedTuple`

In [86]:
t = (word = "hello", num = 1.2, sym = :foo)

(word = "hello", num = 1.2, sym = :foo)

Os valores podem ser acessados como se fossem "campos", usando um ponto:

In [45]:
t.word

"hello"

## Dicionários

Semelhante ao Python, Julia tem suporte nativo para dicionários.
Dicionários são uma maneira genérica de mapear chaves para valores.
Por exemplo, um mapa de números inteiros para strings:

In [87]:
d1 = Dict(1 => "A", 2 => "B", 4 => "D")

Dict{Int64, String} with 3 entries:
  4 => "D"
  2 => "B"
  1 => "A"

**Info**
    Mais tipos!
    `Dict{Int64,String}` é um dicionário com chaves `Int64` e valores `String`.

Acessamos um valor usando a chave dentro de colchetes:

In [88]:
d1[2]

"B"

Dicionários podem usar chaves de vários tipos, inclusive misturando tipos de dados:

In [48]:
Dict("A" => 1, "B" => 2.5, "D" => 2 - 3im)

Dict{String, Number} with 3 entries:
  "B" => 2.5
  "A" => 1
  "D" => 2-3im

**Info**
    Os tipos em Julia formam uma hierarquia. Aqui, o tipo de valor do dicionário é
    `Number`, que é uma generalização de `Int64`, `Float64` e
    `Complex{Int}`. Os nós folha nesta hierarquia são chamados de tipos "concretos",
    e todos os outros são chamados de "Abstratos". Em geral, ter variáveis com
    tipos abstratos como `Number` pode levar a código mais lento, então você deve tentar
    garantir que cada elemento em um dicionário ou vetor seja do mesmo tipo. Por exemplo,
    neste caso, poderíamos representar cada elemento como um
    `Complex{Float64}`:

In [89]:
Dict("A" => 1.0 + 0.0im, "B" => 2.5 + 0.0im, "D" => 2.0 - 3.0im)

Dict{String, ComplexF64} with 3 entries:
  "B" => 2.5+0.0im
  "A" => 1.0+0.0im
  "D" => 2.0-3.0im

Dicionários podem ser aninhados:

In [90]:
d2 = Dict("A" => 1, "B" => 2, "D" => Dict(:foo => 3, :bar => 4))
d2["B"]
d2["D"][:foo]

3

## Estruturas

Você pode definir estruturas de dados personalizadas com `struct`:

In [92]:
struct MinhaStruct
    x::Int
    y::String
    z::Dict{Int,Int}
end

Podemos construir uma instância da estrutura usando o nome da estrutura como uma função,
e passando os valores dos campos, em ordem.
Os campos podem ser acessados usando um ponto:

In [93]:
a = MinhaStruct(1, "a", Dict(2 => 3))
a.x

1

In [94]:
typeof(a)

MinhaStruct

Por default, essas estruturas não são mutáveis, ou seja, os campos não podem ser alterados:

In [95]:
try
    a.x = 2
catch err
    showerror(stderr, err)
end

setfield!: immutable struct of type MinhaStruct cannot be changed

No entanto, você pode declarar uma `mutable struct` que é mutável:

In [97]:
mutable struct MinhaStructMutavel
    x::Int
    y::String
    z::Dict{Int,Int}
end

a = MinhaStructMutavel(1, "a", Dict(2 => 3))
println(a.x)
a.x = 2
a

1


MinhaStructMutavel(2, "a", Dict(2 => 3))

## Repetição

Julia tem suporte nativo para iteração no estilo _for-each_ com a sintaxe
`for <valor> in <coleção> end`:

In [98]:
for i in 1:5
    println(i)
end

1
2
3
4
5


**Info**
    Os intervalos são construídos como `início:fim` ou `início:passo:fim`.

In [99]:
for i in 1.2:1.1:5.8
    println(i)
end

1.2
2.3
3.4
4.5
5.6


Isto também funciona com dicionários:

In [100]:
for (chave, valor) in Dict("A" => 1, "B" => 2.5, "D" => 2 - 3im)
    println("$(chave): $(valor)")
end

B: 2.5
A: 1
D: 2 - 3im


Observe que, ao contrário de linguagens baseadas em vetores como MATLAB e R, loops não
resultam necessariamente em uma degradação significativa de desempenho em Julia.

## Controle de Fluxo

O controle de fluxo de execução em Julia é semelhante ao MATLAB,
usando as palavras-chave `if-elseif-else-end`
e os operadores lógicos `||` e `&&` para **ou** e **e**, respectivamente:

In [59]:
for i in 0:5:15
    if i < 5
        println("$(i) é menor que 5")
    elseif i < 10
        println("$(i) é menor que 10")
    else
        if i == 10
            println("o valor é 10")
        else
            println("$(i) é maior que 10")
        end
    end
end

0 é menor que 5
5 é menor que 10
o valor é 10
15 é maior que 10


## Compreensões

Similar a linguagens como Haskell e Python,
Julia suporta o uso de iteradores simples na construção de arrays e dicionários, chamados de compreensões.

Uma lista de inteiros:

In [101]:
[i for i in 1:5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

Matrizes podem ser construídas ao usar índices múltiplos:

In [102]:
[(i, j) for i in 1:5, j in 1:3]

5×3 Matrix{Tuple{Int64, Int64}}:
 (1, 1)  (1, 2)  (1, 3)
 (2, 1)  (2, 2)  (2, 3)
 (3, 1)  (3, 2)  (3, 3)
 (4, 1)  (4, 2)  (4, 3)
 (5, 1)  (5, 2)  (5, 3)

In [103]:
[i * j for i in 1:5, j in 5:10]

5×6 Matrix{Int64}:
  5   6   7   8   9  10
 10  12  14  16  18  20
 15  18  21  24  27  30
 20  24  28  32  36  40
 25  30  35  40  45  50

É possível filtrar os valores usando expressões condicionais:

In [104]:
[i for i in 1:10 if i % 2 == 1]

5-element Vector{Int64}:
 1
 3
 5
 7
 9

Uma sintaxe semelhante pode ser usada para construir dicionários:

In [105]:
Dict("$(i)" => i for i in 1:10 if i % 2 == 1)

Dict{String, Int64} with 5 entries:
  "1" => 1
  "5" => 5
  "7" => 7
  "9" => 9
  "3" => 3

## Funções

Uma função simples é definida usando `function` e `end`:

In [106]:
function print_hello()
    return println("olá")
end
print_hello()

olá


Uma função pode ter argumentos, declarados entre parênteses:

In [107]:
function print_it(x)
    return println(x)
end
print_it("olá")
print_it(1.234)
print_it(:meu_id)

olá
1.234
meu_id


Argumentos opcionais, identificados por um nome de variável, são separados por um `;` dos outros argumentos:

In [108]:
function print_it(x; prefixo = "valor:")
    return println("$(prefixo) $(x)")
end
print_it(1.234)
print_it(1.234; prefixo = "val:")

valor: 1.234
val: 1.234


In [109]:
print_it(1.234; prefixo = :hahaha)

hahaha 1.234


A palavra-chave `return` é usada para especificar os valores de retorno de uma função:

In [110]:
function mult(x; y = 2.0)
    return x * y
end

mult(4.0)
mult(4.0; y = 5.0)

20.0

### Funções anônimas

A sintaxe `input -> output` cria uma função anônima. Essas são mais
úteis quando passadas para outras funções. Por exemplo:

In [111]:
f = x -> x^2
f(2)
map(x -> x^2, 1:4)

4-element Vector{Int64}:
  1
  4
  9
 16

### Parâmetros de tipo

Podemos restringir as entradas de uma função usando parâmetros de tipo, que são
`::` seguido pelo tipo da entrada desejada. Por exemplo:

In [112]:
function foo(x::Int)
    return x^2
end

function foo(x::Float64)
    return exp(x)
end

function foo(x::Number)
    return x + 1
end

foo(2)
foo(2.0)
foo(1 + 1im)

2 + 1im

Mas o que acontece se chamarmos `foo` com algo para o qual não o definimos?

In [113]:
try
    foo([1, 2, 3])
catch err
    showerror(stderr, err)
end

MethodError: no method matching foo(::Vector{Int64})
The function `foo` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  foo(::Float64)
   @ Main In[112]:5
  foo(::Int64)
   @ Main In[112]:1
  foo(::Number)
   @ Main In[112]:9


Um `MethodError` significa que você passou para uma função
um argumento que não corresponde ao tipo que ela estava esperando.
Neste caso, a mensagem de erro diz que não sabe como lidar com um
`Vector{Int64}`, mas sabe como lidar com `Float64`, `Int64` e
`Number`.

**Dica**
    A parte "Candidatos mais próximos" da mensagem de erro pode dar uma
    dica do que era esperado.

### _Broadcasting_

No exemplo acima, não definimos o que fazer se `f` receber um `Vector`.
Julia fornece uma sintaxe conveniente para aplicar `f` em cada elemento de um `array`:
Basta adicionar um `.` entre o nome da função e o parêntese de abertura `(`.
Isso funciona para _qualquer_ função, incluindo funções com múltiplos argumentos.
Por exemplo:

In [114]:
f.([1, 2, 3])

3-element Vector{Int64}:
 1
 4
 9

**Dica**
    Usar _broadcasting_ pode permitir chamar uma função com um argumento de tipo `Vector`, `Matrix` ou `Array`.

## Objetos mutáveis vs imutáveis

Alguns tipos em Julia são *mutáveis*, o que significa que você pode alterar os valores
dentro deles. Um bom exemplo é um array. Você pode modificar o conteúdo de um
array sem precisar criar um novo array.

Em contraste, tipos como `Float64` são *imutáveis*. Você não pode modificar o
conteúdo de um `Float64`.

Isso é algo a se ter em mente ao passar tipos para funções. Por exemplo:

In [74]:
function exemplo_mutabilidade(tipo_mutavel::Vector{Int}, tipo_imutavel::Int)
    tipo_mutavel[1] += 10
    tipo_imutavel   += 10
    println(tipo_mutavel)
    println(tipo_imutavel)
    return
end

tipo_mutavel = [1, 2, 3]
tipo_imutavel = 1

exemplo_mutabilidade(tipo_mutavel, tipo_imutavel)

println("tipo_mutavel: $(tipo_mutavel)")
println("tipo_imutavel: $(tipo_imutavel)")

[11, 2, 3]
11
tipo_mutavel: [11, 2, 3]
tipo_imutavel: 1


Como `Vector{Int}` é um tipo mutável, modificar a variável dentro da
função alterou o valor fora da função. Em contraste, a alteração
em `tipo_imutavel` não modificou o valor fora da função.

Você pode verificar a mutabilidade com a função `isimmutable`:

In [75]:
isimmutable([1, 2, 3])
isimmutable(1)

true

## `Pkg`, o gerenciador de pacotes

### Instalando pacotes

Não importa quão maravilhosa seja a linguagem Julia, em algum momento você vai querer usar um pacote.
Alguns desses estão integrados, por exemplo, a geração de
números aleatórios está disponível no pacote `Random` da biblioteca padrão.
Esses pacotes são carregados com os comandos `using` e `import`.

In [76]:
using Random  # Equivalente a `from Random import *` em python
import Random  # Equivalente a `import Random` em python

Random.seed!(33)

[rand() for i in 1:10]

10-element Vector{Float64}:
 0.4745319377345316
 0.9650392357070774
 0.8194019096093067
 0.9297749959069098
 0.3127122336048005
 0.9684448191382753
 0.9063743823581542
 0.8386731983150535
 0.5103924401614957
 0.9296414851080324

O Gerenciador de Pacotes é usado para instalar pacotes que não fazem parte da
biblioteca padrão da Julia.

Por exemplo, é assim que instalamos o pacote `JuMP`:
```julia
using Pkg
Pkg.add("JuMP")
```

O [JuliaHub](https://juliahub.com) tem uma lista completa dos pacotes Julia registrados.

De vez em quando, você pode desejar usar um pacote Julia que não está registrado. Nesse
caso, uma URL do repositório git pode ser usada para instalar o pacote.
```julia
using Pkg
Pkg.add("https://github.com/user-name/MyPackage.jl.git")
```

### Ambientes de pacotes

O comando `Pkg.add` adicionará pacotes ao ambiente "corrente" do Julia.
No entanto, Julia também tem suporte integrado para ambientes virtuais (um pouco como `virtualenv` em python).

Ative um ambiente virtual com:
```julia
import Pkg; Pkg.activate("/caminho/para/ambiente")
```

Você pode ver quais pacotes estão instalados no ambiente atual com
`Pkg.status()`.

**Dica**
    Recomendamos _fortemente_ que você crie um ambiente Pkg para cada projeto
    que criar em Julia, e adicione apenas os pacotes que precisa, em vez de adicionar
    muitos pacotes ao ambiente global. A [documentação do gerenciador de pacotes](https://julialang.github.io/Pkg.jl/v1/environments/)
    possui mais informações sobre esse tópico.